### ISSUE TITLE
Awesome Project

### ISSUE THREAD

**Issue by seflless** [winfinit/mongodb-prebuilt#1]
Are you using this in production? I was just starting to build this exact project and then went to `npm publish` and realized it was already take. I'm doing a lot of Electron work right now and this seems perfect for that. 

Looks polished! Quick question too: Does install it non globally polute anything onto a computer or is it all full self contained into a project's `node_modules/`?

**Comment by winfinit** [comment]
thank you! it is self contained, only if you specify -g, it will create symlinks for supplied binaries. This is my preferred method of installing now.

**Comment by seflless** [comment]
Awesome, how are you using this project out of curiousity?

**Comment by winfinit** [comment]
currently i use it as convenient cross platform installer, however my motivation is to make a self contained application, where one doesnt have to worry about having a database and/or session storage running before starting your application (that is of course for small non clustered applications). I also think it is pretty convenient to run application with nodejs as a wrapper, you get a convenient streamed logs that you can have access to without tailing consistently log file, which can also rotate, etc...

another immediate motivation for this project is Mockgoose project, currently that project is mocking mongoose, which I disagree with that approach, so I want to utilize in memory storage engine that can be used during integration testing or model that requires some database interactions.

**Comment by seflless** [comment]
Yeah, just a convenient cross platform installer is a good enough reason. MongoDB Inc should totally support that. 

Interesting, haven't tried that out. I'm working on a lib to make it easy to make a collaborative desktop app. Think multi person sketching, diagramming, etc. Nothing I'm rushing out, too busy with the day job and related side projects.

Again, you rock for building this out and properly polishing it to work cross platform.
