### ISSUE TITLE
Prevents parent process from exiting

### ISSUE THREAD

**Issue by hgcummings** [winfinit/mongodb-prebuilt#15]
Starting mongodb now prevents the parent process from exiting correctly. This is because it spawns a connected child process that contains a setInterval, so the event loop never empties.

Fix coming soon to a PR near you.

**Comment by winfinit** [comment]
@hgcummings is this resolved at this point? if so, can you please close this ticket?

**Comment by hgcummings** [comment]
Yes, thank you, resolved since the release including the linked PR.
