### ISSUE TITLE
Error installing mockgoose

### ISSUE THREAD

**Issue by Nokel81** [winfinit/mongodb-prebuilt#19]
When I do "npm i mockgoose" I get this error

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: unexpected end of file
>     at Zlib._handle.onerror (zlib.js:363:17)
> npm ERR! Darwin 15.2.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "mockgoose"
> npm ERR! node v5.3.0
> npm ERR! npm  v3.3.12
> npm ERR! code ELIFECYCLE
> 
> npm ERR! mongodb-prebuilt@4.6.0 postinstall: `node install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the mongodb-prebuilt@4.6.0 postinstall script 'node install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the mongodb-prebuilt package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node install.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls mongodb-prebuilt
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/smalton/Vader/hermes.svc/npm-debug.log`

**Comment by winfinit** [comment]
@Nokel81 please run npm install with debug env

```
DEBUG=* npm install
```

**Comment by braker1nine** [comment]
@winfinit Just ran with `DEBUG=*`

>  DEBUG=\* npm install --save-dev mockgoose
> 
> > spawn-sync@1.0.15 postinstall /Users/Chris/Development/Outshape/Backend/node_modules/spawn-sync
> > node postinstall
> 
> > mongodb-prebuilt@5.0.3 postinstall /Users/Chris/Development/Outshape/Backend/node_modules/mongodb-prebuilt
> > node install.js
> 
> done
>   mongodb-prebuilt installing version: 3.2.0 +0ms
>   mongodb-download selected platform osx +3ms
>   mongodb-download selected architecture x86_64 +2ms
>   mongodb-download selected version: 3.2.0 +0ms
>   mongodb-download selected archive tgz +1ms
>   mongodb-download final name: mongodb-osx-x86_64-3.2.0.tgz +0ms
>   mongodb-download final download URI: https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-3.2.0.tgz +0ms
>   mongodb-download download directory: /var/folders/wj/wg6fg1ws4r3gwjmrfxjdfmf80000gn/T +1ms
>   mongodb-download download complete path: /var/folders/wj/wg6fg1ws4r3gwjmrfxjdfmf80000gn/T/mongodb-download/mongodb-osx-x86_64-3.2.0.tgz +0ms
>   mongodb-download sending file from cache +0ms
>   mongodb-prebuilt archive type selected targz +1ms
> events.js:154
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: unexpected end of file
>     at Zlib._handle.onerror (zlib.js:370:17)
> Outshape@1.0.0 /Users/Chris/Development/Outshape/Backend
> └── (empty)
> 
> npm WARN Outshape@1.0.0 No repository field.
> npm WARN Outshape@1.0.0 No license field.
> npm ERR! Darwin 15.4.0
> npm ERR! argv "/Users/Chris/.n/bin/node" "/Users/Chris/.n/bin/npm" "install" "--save-dev" "mockgoose"
> npm ERR! node v5.11.0
> npm ERR! npm  v3.8.6
> npm ERR! code ELIFECYCLE
> 
> npm ERR! mongodb-prebuilt@5.0.3 postinstall: `node install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the mongodb-prebuilt@5.0.3 postinstall script 'node install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the mongodb-prebuilt package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mongodb-prebuilt
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls mongodb-prebuilt
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/Chris/Development/Outshape/Backend/npm-debug.log
> npm ERR! code 1

**Comment by winfinit** [comment]
I wonder if you have tgz that was not completely downloaded, can you please try again, and see if you are getting same error, if you do, please try to remove tgz from tmp folder, and try again (in your case you  would want to delete /var/folders/wj/wg6fg1ws4r3gwjmrfxjdfmf80000gn/T/mongodb-download/mongodb-osx-x86_64-3.2.0.tgz)

**Comment by traviisd** [comment]
I also get an error, but mine is related to  local issuer certificate. I am running the install as administrator on Windows 10. Any help would be appreciated.

$ DEBUG=* npm install mockgoose

> spawn-sync@1.0.15 postinstall C:\github\test\node_modules\spawn-sync
> node postinstall


> mongodb-prebuilt@5.0.8 postinstall C:\github\test\node_modules\mongodb-prebuilt
> node install.js

done
Sat, 11 Feb 2017 04:13:11 GMT mongodb-prebuilt installing version: 3.2.10
Sat, 11 Feb 2017 04:13:11 GMT mongodb-download selected platform win32
Sat, 11 Feb 2017 04:13:11 GMT mongodb-download selected architecture x86_64
Sat, 11 Feb 2017 04:13:11 GMT mongodb-download selected version: 3.2.10
Sat, 11 Feb 2017 04:13:11 GMT mongodb-download selected archive zip
Sat, 11 Feb 2017 04:13:11 GMT mongodb-download final name: mongodb-win32-x86_64-3.2.10.zip
Sat, 11 Feb 2017 04:13:11 GMT mongodb-download final download URI: https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-3.2.10.zip
Sat, 11 Feb 2017 04:13:11 GMT mongodb-download download directory: C:\Users\fake\AppData\Local\Temp
Sat, 11 Feb 2017 04:13:11 GMT mongodb-download download complete path: C:\Users\fake\AppData\Local\Temp\mongodb-download\mongodb-win32-x86_64-3.2.10.zip
Sat, 11 Feb 2017 04:13:11 GMT mongodb-download http opts: { protocol: 'https:',
  hostname: 'fastdl.mongodb.org',
  path: '/win32/mongodb-win32-x86_64-3.2.10.zip' }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
test@1.0.3 C:\github\test
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN test@1.0.3 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mockgoose"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mongodb-prebuilt@5.0.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mongodb-prebuilt@5.0.8 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mongodb-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mongodb-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mongodb-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\github\test\npm-debug.log
npm ERR! code 1

**Comment by winfinit** [comment]
can you please attempt to use latest release and tell me if you are still getting this error?

**Comment by petershaw** [comment]
I solved this issue by removing /tmp/mongo-download, install mockgoose@6.0.8, and than run `node install.js` by hand in `/node_modules/mongodb-prebuilt` before i run the rest install with npm install.
Maybe it's a timing issue?

**Comment by winfinit** [comment]
I had several race conditions that were resolved with latest release, so that would be a safe guess.

**Comment by stonedndead** [comment]
Hi Guys,

I am facing the same issue while installing Ignite web console.
I am running npm install --no-optional

3716 warn   path: 'C:\\Working\\Ignite\\apache-ignite-2.1.0-src\\modules\\web-console\\backend\\node_modules\\parse-glob\\node_modules' }
3718 verbose stack Error: mongodb-prebuilt@5.0.8 postinstall: `node install.js`
3718 verbose stack Exit status 1
3718 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
3718 verbose stack     at emitTwo (events.js:125:13)
3718 verbose stack     at EventEmitter.emit (events.js:213:7)
3718 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
3718 verbose stack     at emitTwo (events.js:125:13)
3718 verbose stack     at ChildProcess.emit (events.js:213:7)
3718 verbose stack     at maybeClose (internal/child_process.js:927:16)
3718 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
3719 verbose pkgid mongodb-prebuilt@5.0.8
3720 verbose cwd C:\Working\Ignite\apache-ignite-2.1.0-src\modules\web-console\backend
3721 verbose Windows_NT 6.1.7601
3722 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-optional"
3723 verbose node v8.5.0
3724 verbose npm  v5.3.0
3725 error code ELIFECYCLE
3726 error errno 1
3727 error mongodb-prebuilt@5.0.8 postinstall: `node install.js`
3727 error Exit status 1
3728 error Failed at the mongodb-prebuilt@5.0.8 postinstall script.
3728 error This is probably not a problem with npm. There is likely additional logging output above.
3729 verbose exit [ 1, true ]

**Comment by albertlieyingadrian** [comment]
I'm facing the same issue. Anyone know how to solve this?

**Comment by Nor-Wiener** [comment]
@stonedndead 
You can remove "mockgoose": "6.0.8", line from package.json
It works for me
