### ISSUE TITLE
Pass proxy to mongodb-download

### ISSUE THREAD

**Issue by YellowDarter** [winfinit/mongodb-prebuilt#20]
When behind a corporate proxy, the post install task (node install.js) fails.  This appears to be a failure to pass the npm proxy settings through to install.js.

**Comment by BenCoffman** [comment]
Agree with @AdamYoungberg  :+1:

**Comment by winfinit** [comment]
I've released new version of Mockgoose 6.0.0 there are small modifications to your unit tests that you would have to do, but it will save you a lot of headache in the future, if you will convert to 6.0 release, that also incorporates requested feature here.

https://www.npmjs.com/package/mongodb-prebuilt#download-proxy

**Comment by YellowDarter** [comment]
Hooray!  Thanks this is working beautifully.
