### ISSUE TITLE
error installing mockgoose on elasticbean

### ISSUE THREAD

**Issue by basantgollapudi** [winfinit/mongodb-prebuilt#24]
i see the below error in eb logs. 

> mongodb-prebuilt@5.0.3 postinstall /tmp/deployment/application/node_modules/mockgoose/node_modules/mongodb-prebuilt
> node install.js

  done
  /tmp/deployment/application/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/index.js:81
                                throw e;
                                ^

  Error: No unique release file found!
      at /tmp/deployment/application/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/index.js:136:21
      at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by winfinit** [comment]
can you please help me to test this again with 6.x release (i understand that this issue is being open for a very long time now)

**Comment by basantgollapudi** [comment]
okk, i think we resolved it. forgot to close it. thank you.
