### ISSUE TITLE
Don't works on windows cause forking.

### ISSUE THREAD

**Issue by StarpTech** [winfinit/mongodb-prebuilt#29]
Hi,
on windows there is no `--fork` option. I get this error from the logs. Thank you.

```
 mongodb Error parsing command line: unrecognised option '--fork'
```

When I set fork to `false` the server terminates with code 100.

**Comment by blacksun1** [comment]
Hi, I would appreciate an update on this issue also.

**Comment by winfinit** [comment]
this was deprecated in our new release
