### ISSUE TITLE
Use proxy environment variable

### ISSUE THREAD

**Issue by Dinistro** [winfinit/mongodb-prebuilt#34]
Currently you can only find the environment variable `npm_config_https_proxy` in the install script. In some special cases, it's possible that npm itself doesn't use a proxy, but the install script should. So is it possible to add 

`if (argv.http_proxy || process.env.npm_config_https_proxy || process.env.https_proxy) {`

in the install script?

**Comment by winfinit** [comment]
published 5.0.7 with requested change
