### ISSUE TITLE
mongodb 3.4 update

### ISSUE THREAD

**Issue by asaf-romano** [winfinit/mongodb-prebuilt#36]
Hi,

I got this error running some test (through mockgoose):  Unrecognized pipeline stage name: '$replaceRoot'

I guess this is because mongodb-prebuilt still runs on 3.2. What does it take to update it to 3.4? I'd happily submit a PR.

**Comment by winfinit** [comment]
this was resolved with latest release, now by default "latest" is being used

**Comment by asaf-romano** [comment]
Thanks!
