### ISSUE TITLE
how to shutdown server

### ISSUE THREAD

**Issue by seriousManual** [winfinit/mongodb-prebuilt#38]
In the documentation you mention that via the mongodb helper the server can be started.
Is there any way to shutdown that server instance programatically?

**Comment by smelted-code** [comment]
Ideally we'd have a function we could invoke that would terminate the spawned process. But in the meantime, I hope this unblocks folks:  

```
new MongoBins("mongo", ["--eval", "db.getSiblingDB('admin').shutdownServer()"]).run();
```

Don't forget to pass in your port if it's not the default.

There's probably some slicker mongo-fu out there. Answer provided without warranty, etc. etc.

References:
* https://stackoverflow.com/questions/11774887/how-to-stop-mongo-db-in-one-command
* https://docs.mongodb.com/manual/tutorial/manage-mongodb-processes/

**Comment by winfinit** [comment]
this is great, thank you, I will add a helper function.

**Comment by StarpTech** [comment]
Any updates? @winfinit should be easy to provide a function to exit the child process. Do you accept PR?

**Comment by winfinit** [comment]
Hello Dusting,

PRs are always welcome! I’ve meant to fix this one for a while now, but just didn’t get around it yet.
