### ISSUE TITLE
Override the download path of mongodb

### ISSUE THREAD

**Issue by hiro5id** [winfinit/mongodb-prebuilt#42]
Is there a way to override the default download path?  Currently on Mac it appears to download the .tgz file  some where in `/var/folders/l_/qwg41g_d1zn8ggjbjz0ctp1m0000gn/T/mongodb-download/`  I would like to override that, because it would be helpful when working with docker containers.

**Comment by LoneRifle** [comment]
I'm not sure if the PR I just merged would help you as I don't know if you're using mongodb-prebuilt via CLI or programmatically. The former isn't currently supported and would take some work to put into place
