### ISSUE TITLE
Error installing Mockgoose in Docker

### ISSUE THREAD

**Issue by franky-continu** [winfinit/mongodb-prebuilt#5]
npm info lifecycle mongodb-prebuilt@4.2.13~postinstall: mongodb-prebuilt@4.2.13

> mongodb-prebuilt@4.2.13 postinstall /usr/src/app/node_modules/mongodb-prebuilt
> node install.js
> /usr/src/app/node_modules/mongodb-download/index.js:127
> throw new Error("unsupported release of Debian " + os.release);
> ^
> Error: unsupported release of Debian 8.2
> at /usr/src/app/node_modules/mongodb-download/index.js:127:12
> at /usr/src/app/node_modules/getos/index.js:65:18
> at releasefile (/usr/src/app/node_modules/getos/logic/debian.js:25:3)
> at /usr/src/app/node_modules/getos/logic/debian.js:13:18
> at ChildProcess.exithandler (child_process.js:220:5)
> at emitTwo (events.js:87:13)
> at ChildProcess.emit (events.js:172:7)
> at maybeClose (internal/child_process.js:818:16)
> at Socket.<anonymous> (internal/child_process.js:319:11)
> at emitOne (events.js:77:13)
> npm info lifecycle mongodb-prebuilt@4.2.13~postinstall: Failed to exec postinstall script

npm WARN EPEERINVALID mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.1.0
npm ERR! npm v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! mongodb-prebuilt@4.2.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mongodb-prebuilt@4.2.13 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mongodb-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node install.js
npm ERR! You can get their info via:
npm ERR! npm owner ls mongodb-prebuilt
npm ERR! There is likely additional logging output above.

**Comment by winfinit** [comment]
@franky-continu this is resolved now also, right?

**Comment by franky-continu** [comment]
Sure thing Roman, thanks
Franky Diaz-Trepat
Full Stack Engineer
+1 (720) 295-0592 / 401-1276
skype: franky.diaz.trepat
franky@continu.co
