### ISSUE TITLE
How can we know version of mongodb?

### ISSUE THREAD

**Issue by Martinsos** [winfinit/mongodb-prebuilt#50]
Hi!
Thanks for this repo.
Information that I could not find is to which mongodb version does a specific version of mongodb-prebuilt relate to? So if I have mongodb-prebuilt 5.0.8, which version of mongo is that? Or if I want 2.2.43 mongodb, which version of mongodb-prebuilt should I be looking for? Thanks!

**Comment by skerit** [comment]
This package uses [mongodb-download](https://github.com/winfinit/mongodb-download) (also made by winfinit) to actually download the binary. THAT package accepts a `version` option which defaults to the latest version, but this package doesn't pass any `version` option to it. So it's always using the latest version.

So right now I think it's impossible to use older mongodb versions :/
